deployment:
  name: apiproxy-deploy
  namespace: ssltest
  labels:
    app: apiproxy-deploy
    version: v1
  selectorLabels:
    app: apiproxy-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1
  nodeSelector:
    agentpool: aksapipool
  containers:
  - name: apiproxy-app
    image: akstrnacr.azurecr.io/apiproxyapp:v1.0.0
    imagePullPolicy: IfNotPresent
    memoryRequest: "64Mi"
    cpuRequest: "100m"
    memoryLimit: "256Mi"
    cpuLimit: "200m"
    containerPorts: [8081, 8443]    
    env:
    - name: API_URL
      value: "https://apibkendwks.internal.wkshpdev.com"
    - name: KEY_FILENAME
      value: ""
    - name: CERT_FILENAME
      value: ""
service:
  name: apiproxy-service
  namespace: ssltest
  selector:
    app: apiproxy-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8081
  - protocol: TCP
    name: https
    port: 443
    targetPort: 8443