deployment:
  name: apibkend-deploy
  namespace: ssltest
  labels:
    app: apibkend-deploy
    version: v1
  selectorLabels:
    app: apibkend-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1
  nodeSelector:
    agentpool: aksapipool
  containers:
  - name: apibkend-app
    image: akstrnacr.azurecr.io/apibkendapp:v1.0.0
    imagePullPolicy: IfNotPresent
    memoryRequest: "64Mi"
    cpuRequest: "100m"
    memoryLimit: "256Mi"
    cpuLimit: "200m"
    containerPorts: [9081, 9443]    
    env:
    - name: KEY_FILENAME
      value: ""
    - name: CERT_FILENAME
      value: ""
service:
  name: apibkend-service
  namespace: ssltest
  selector:
    app: apibkend-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 9081
  - protocol: TCP
    name: https
    port: 443
    targetPort: 9443